FROM gcc-with-sonar-scanner-cli:latest

LABEL maintainer="falko.schwabe@googlemail.com"
LABEL version="1.0.0"
LABEL description="Provides a cross-compile environment for windows x64."

#RUN apt-get update \
#  && apt-get install -y --no-install-recommends

USER scanner-cli
