FROM atlassianlabs/docker-node-jdk-chrome-firefox:2020-02-17

LABEL maintainer="falko.schwabe@googlemail.com"
LABEL version="1.0.0"
LABEL description="Provides an extended toolchain for nodejs builds."

RUN apt-get update \
    && apt-get install -y --no-install-recommends rsync
